# Generated by Django 5.2.6 on 2025-09-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuelo',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
    ]
